### ISSUE TITLE
Countdown/Timer

### ISSUE THREAD

**Issue by hiferli** [harshchandwani/react-code-snippets#1]
Countdown Component that can be added in React that takes minutes and seconds as props and counts until the time ends.
Would love to add this component that I used once in my application (Link: https://quix-ten.vercel.app/).

Please assign this issue to me so that I can proceed further.

**Comment by harshchandwani** [comment]
You can work on it

**Comment by hiferli** [comment]
Thanks for the issue.
I'll start working
